language: go

addons:
  postgresql: "10"

services:
  - postgresql

env:
  REV_DSN: "travis:@localhost:5432/revisioneer"

before_script:
  - psql -c 'create database revisioneer;' -U postgres

go:
  - 1.13
